[metadata]
name = magnetic_cataclysmic_variables
version = 0.1.0
author = Clément Mur
description = Evaluate magnetic cataclysmic variable stars (mCVs) candidates using ZTF data and Fink API.
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Intended Audience :: Science/Research
    Topic :: Scientific/Engineering :: Astronomy
    Operating System :: OS Independent

[options]
packages = find:
include_package_data = True
python_requires = >=3.8
install_requires =
    pandas
    numpy
    scikit-learn
    requests
    tqdm
    pyarrow
    light-curve

[options.package_data]
mcvs = data/*.csv, data/*.parquet

